-- ============================================================
--  学級日誌 (school-system) — PostgreSQL schema
--  Соответствует JPA-сущностям (com.school.model.*).
--  В приложении схема создаётся автоматически (ddl-auto=update);
--  этот скрипт — ручной эквивалент для документации/чистой установки.
-- ============================================================

-- --- 1) Создание базы (выполнять отдельно, вне транзакции) --------------
--   В psql:   CREATE DATABASE school;  \c school
--   Или CLI:  createdb school
-- CREATE DATABASE school WITH ENCODING 'UTF8';

-- --- 2) Таблицы ----------------------------------------------------------

-- Пользователи (администраторы, преподаватели, студенты)
CREATE TABLE app_user (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(255) NOT NULL,
    password         VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    first_name       VARCHAR(255) NOT NULL,
    role             VARCHAR(255) NOT NULL,          -- ADMIN | TEACHER | STUDENT
    student_number   VARCHAR(255),                   -- только у студентов (6 цифр)
    photo_name       VARCHAR(255),
    school_class_id  BIGINT,                          -- только у студентов
    CONSTRAINT uq_app_user_username       UNIQUE (username),
    CONSTRAINT uq_app_user_student_number UNIQUE (student_number)
);

-- Учебные группы (1年A組)
CREATE TABLE school_class (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_year     INTEGER      NOT NULL,
    group_code     VARCHAR(255) NOT NULL,
    supervisor_id  BIGINT,                            -- классный руководитель (担任)
    CONSTRAINT uq_school_class_year_group UNIQUE (study_year, group_code)
);

-- Предметы
CREATE TABLE subject (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    CONSTRAINT uq_subject_name UNIQUE (name)
);

-- Недельный шаблон расписания (повторяющийся слот)
CREATE TABLE schedule_template (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id  BIGINT       NOT NULL,
    subject_id       BIGINT       NOT NULL,
    teacher_id       BIGINT       NOT NULL,
    day_of_week      VARCHAR(255) NOT NULL,           -- MONDAY..SUNDAY
    start_time       TIME         NOT NULL,
    end_time         TIME         NOT NULL,
    room             VARCHAR(255)
);

-- Конкретный урок (сгенерирован из шаблона)
CREATE TABLE lesson (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date             DATE   NOT NULL,
    start_time       TIME   NOT NULL,
    end_time         TIME   NOT NULL,
    school_class_id  BIGINT NOT NULL,
    subject_id       BIGINT NOT NULL,
    teacher_id       BIGINT NOT NULL,
    room             VARCHAR(255)
);

-- Оценки (5-балльная шкала: 2..5)
CREATE TABLE grade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT  NOT NULL,
    lesson_id   BIGINT  NOT NULL,
    value       INTEGER NOT NULL
);

-- Посещаемость
CREATE TABLE attendance (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT       NOT NULL,
    lesson_id   BIGINT       NOT NULL,
    status      VARCHAR(255) NOT NULL                 -- PRESENT | LATE | ABSENT | EXCUSED
);

-- Заметки студента (по дню); for_teacher = видна преподавателям
CREATE TABLE student_note (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   BIGINT        NOT NULL,
    date         DATE          NOT NULL,
    text         VARCHAR(2000) NOT NULL,
    for_teacher  BOOLEAN       NOT NULL DEFAULT FALSE
);

-- Комментарии преподавателя к уроку
CREATE TABLE teacher_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id   BIGINT        NOT NULL,
    author_id   BIGINT        NOT NULL,
    text        VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP     NOT NULL
);

-- Файлы, прикреплённые к уроку
CREATE TABLE file_attachment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id       BIGINT       NOT NULL,
    uploaded_by_id  BIGINT       NOT NULL,
    original_name   VARCHAR(255) NOT NULL,
    stored_name     VARCHAR(255) NOT NULL,
    uploaded_at     TIMESTAMP    NOT NULL
);

-- События/уведомления для группы (試験 / アクティビティ)
CREATE TABLE school_event (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id  BIGINT        NOT NULL,
    date             DATE          NOT NULL,
    title            VARCHAR(255)  NOT NULL,
    type             VARCHAR(255)  NOT NULL,          -- EXAM | ACTIVITY
    description      VARCHAR(2000),
    created_by_id    BIGINT
);

-- --- 3) Внешние ключи (после создания всех таблиц из-за циклической связи
--         app_user <-> school_class) ------------------------------------

ALTER TABLE app_user
    ADD CONSTRAINT fk_app_user_class      FOREIGN KEY (school_class_id) REFERENCES school_class (id);

ALTER TABLE school_class
    ADD CONSTRAINT fk_class_supervisor    FOREIGN KEY (supervisor_id)   REFERENCES app_user (id);

ALTER TABLE schedule_template
    ADD CONSTRAINT fk_tpl_class           FOREIGN KEY (school_class_id) REFERENCES school_class (id),
    ADD CONSTRAINT fk_tpl_subject         FOREIGN KEY (subject_id)      REFERENCES subject (id),
    ADD CONSTRAINT fk_tpl_teacher         FOREIGN KEY (teacher_id)      REFERENCES app_user (id);

ALTER TABLE lesson
    ADD CONSTRAINT fk_lesson_class        FOREIGN KEY (school_class_id) REFERENCES school_class (id),
    ADD CONSTRAINT fk_lesson_subject      FOREIGN KEY (subject_id)      REFERENCES subject (id),
    ADD CONSTRAINT fk_lesson_teacher      FOREIGN KEY (teacher_id)      REFERENCES app_user (id);

ALTER TABLE grade
    ADD CONSTRAINT fk_grade_student       FOREIGN KEY (student_id)      REFERENCES app_user (id),
    ADD CONSTRAINT fk_grade_lesson        FOREIGN KEY (lesson_id)       REFERENCES lesson (id);

ALTER TABLE attendance
    ADD CONSTRAINT fk_att_student         FOREIGN KEY (student_id)      REFERENCES app_user (id),
    ADD CONSTRAINT fk_att_lesson          FOREIGN KEY (lesson_id)       REFERENCES lesson (id);

ALTER TABLE student_note
    ADD CONSTRAINT fk_note_student        FOREIGN KEY (student_id)      REFERENCES app_user (id);

ALTER TABLE teacher_comment
    ADD CONSTRAINT fk_comment_lesson      FOREIGN KEY (lesson_id)       REFERENCES lesson (id),
    ADD CONSTRAINT fk_comment_author      FOREIGN KEY (author_id)       REFERENCES app_user (id);

ALTER TABLE file_attachment
    ADD CONSTRAINT fk_file_lesson         FOREIGN KEY (lesson_id)       REFERENCES lesson (id),
    ADD CONSTRAINT fk_file_uploader       FOREIGN KEY (uploaded_by_id)  REFERENCES app_user (id);

ALTER TABLE school_event
    ADD CONSTRAINT fk_event_class         FOREIGN KEY (school_class_id) REFERENCES school_class (id),
    ADD CONSTRAINT fk_event_author        FOREIGN KEY (created_by_id)   REFERENCES app_user (id);

-- --- 4) (Опционально) индексы под частые выборки -------------------------
CREATE INDEX idx_lesson_class_date  ON lesson (school_class_id, date);
CREATE INDEX idx_lesson_teacher     ON lesson (teacher_id, date);
CREATE INDEX idx_grade_lesson       ON grade (lesson_id);
CREATE INDEX idx_attendance_lesson  ON attendance (lesson_id);
CREATE INDEX idx_event_class_date   ON school_event (school_class_id, date);
CREATE INDEX idx_note_student_date  ON student_note (student_id, date);
